### ISSUE TITLE
bug: usePrepareContractWrite fails if chainId is not 1

### ISSUE THREAD

**Issue by actuallymentor** [wagmi-dev/wagmi#1222]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.7.9

### Current Behavior

When calling `usePrepareContractWrite` while the user's wallet is connected to a non-1 chainId, the preparation and consecutive `useContractWrite` fails.

### Expected Behavior

Preparation should succeed.

### Steps To Reproduce

1. Open https://codesandbox.io/s/nostalgic-wilson-6td2dy?file=/src/App.js
2. Set your wallet to Polygon (chain ID 137)
3. Click the connect button
4. Watch the interface fail

Note how at no point was the chain ID 1.

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://codesandbox.io/s/nostalgic-wilson-6td2dy?file=/src/App.js

### Anything else?

Thanks for your work on this package!

**Comment by paOol** [comment]
I've definitely done contract writes on localhost  (chainid: 31337), so I don't think there is a "bug".

however, you might want to look at how you're configuring chains and cleating clients, because that's likely where your issue is.

**Comment by sb777** [comment]
Right. As a starting point, Polygon is not in defaultChains.

**Comment by fonzarely** [comment]
I guess I have the same issue with Goerli. I can't launch any transaction nor receive tx hash.

**Comment by sb777** [comment]
@actuallymentor Wrangling your providers, chains and endpoints is the most challenging part of getting this all going, keep pushing through it and monitoring your network requests is the best way to figure out what's going on. Then you will be able to set up everything perfectly. Remember Wagmi provides a public Provider which will get you going but you will likely want to configure your own endpoints for your app. And any local testnets or other chains.

**Comment by tmm** [comment]
This was, in fact, a bug. Thanks for reporting! Fixed in #1232 and added a more helpful error message.

**Comment by tong0x** [comment]
> I guess I have the same issue with Goerli. I can't launch any transaction nor receive tx hash.

I'm also still having this issue, even after upgrading to v0.7.13

**Comment by tmm** [comment]
@tong0x can you drop a link to a minimal reproducible example?
