### ISSUE TITLE
InjectedConnector is not exported from @wagmi/core

### ISSUE THREAD

**Issue by challet** [wagmi-dev/wagmi#1459]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.8.2

### Current Behavior

```
Module not found: Error: Package path ./connectors/injected is not exported from package /[…]/node_modules/@wagmi/core (see exports field in /[…]/node_modules/@wagmi/core/package.json)
```

### Expected Behavior

Can import `InjectedConnector`

### Steps To Reproduce

* copy code from https://wagmi.sh/core/connectors/injected
* run

### Anything else?

It surprised me and I may have missed something but I haven't found any reference to it in https://github.com/wagmi-dev/wagmi/blob/0.8.x/packages/core/package.json, contrary to the one from the react package.

**Comment by jxom** [comment]
You can import it directly from `wagmi/connectors`!

```ts
import { InjectedConnector } from 'wagmi/connectors'
```

I have updated the docs to reflect this via #1460

**Comment by challet** [comment]
@jxom Thank you but I'm sorry it still doesn't work : 
```
Module not found: Error: Package path ./connectors is not exported from package
```

It seems there is a confusion between the 2 packages `wagmi` and `@wagmi/core` : I'm only using the latter while indeed `connectors/injected` is exported on the former, as seen on the following diff from my node_modules with both packages installed :

```diff
--- wagmi/package.json
+++ @wagmi/core/package.json
@@ -1,128 +1,123 @@
 {
-  "name": "wagmi",
-  "description": "React Hooks for Ethereum",
+  "name": "@wagmi/core",
+  "description": "Vanilla JS library for Ethereum",
   "license": "MIT",
-  "version": "0.9.2",
+  "version": "0.8.2",
   "repository": {
     "type": "git",
     "url": "https://github.com/wagmi-dev/wagmi.git",
-    "directory": "packages/react"
+    "directory": "packages/core"
   },
[…]
   "exports": {
     ".": {
       "types": "./dist/index.d.ts",
       "default": "./dist/index.js"
     },
-    "./actions": {
-      "types": "./dist/actions.d.ts",
-      "default": "./dist/actions.js"
-    },
     "./chains": {
       "types": "./dist/chains.d.ts",
       "default": "./dist/chains.js"
     },
     "./connectors/coinbaseWallet": {
       "types": "./dist/connectors/coinbaseWallet.d.ts",
       "default": "./dist/connectors/coinbaseWallet.js"
     },
-    "./connectors/injected": {
-      "types": "./dist/connectors/injected.d.ts",
-      "default": "./dist/connectors/injected.js"
-    },
     "./connectors/metaMask": {
       "types": "./dist/connectors/metaMask.d.ts",
       "default": "./dist/connectors/metaMask.js"
     },
     "./connectors/mock": {
-      "types": "./dist/connectors/mock.d.ts",
-      "default": "./dist/connectors/mock.js"
+      "types": "./dist/connectors/mock/index.d.ts",
+      "default": "./dist/connectors/mock/index.js"
     },
     "./connectors/walletConnect": {
       "types": "./dist/connectors/walletConnect.d.ts",
       "default": "./dist/connectors/walletConnect.js"
     },
-    "./providers/alchemy": {
-      "types": "./dist/providers/alchemy.d.ts",
-      "default": "./dist/providers/alchemy.js"
+    "./internal": {
+      "types": "./dist/internal/index.d.ts",
+      "default": "./dist/internal/index.js"
     },
+    "./internal/test": {
+      "types": "./dist/internal/test.d.ts",
+      "default": "./dist/internal/test.js"
+    },
     "./providers/infura": {
       "types": "./dist/providers/infura.d.ts",
       "default": "./dist/providers/infura.js"
     },
-    "./providers/jsonRpc": {
-      "types": "./dist/providers/jsonRpc.d.ts",
-      "default": "./dist/providers/jsonRpc.js"
-    },
     "./providers/public": {
       "types": "./dist/providers/public.d.ts",
       "default": "./dist/providers/public.js"
     },
+    "./providers/alchemy": {
+      "types": "./dist/providers/alchemy.d.ts",
+      "default": "./dist/providers/alchemy.js"
+    },
+    "./providers/jsonRpc": {
+      "types": "./dist/providers/jsonRpc.d.ts",
+      "default": "./dist/providers/jsonRpc.js"
+    },
     "./package.json": "./package.json"
   },
   "sideEffects": false,
   "files": [
-    "/actions",
     "/chains",
     "/connectors",
-    "/dist",
-    "/providers"
+    "/internal",
+    "/providers",
+    "/dist"
   ],
[…]
 }
```

**Comment by challet** [comment]
I don't fully understand how the two packages interact with each other and if `@wagmi/core` is supposed to work standalone. If that's the case, I can then make a PR to add the missing export.

**Comment by tmm** [comment]
`wagmi` is a React adapter for `@wagmi/core`. The docs still weren't correct so I just fixed them. `InjectedConnector` is importable directly from `@wagmi/core` since it doesn't have any third-party dependencies and is the default used in `Client`.

```ts
import { InjectedConnector } from '@wagmi/core'
```

In `wagmi`, all the Connectors are seperate entrypoints (e.g. `wagmi/connectors/<connector_name>`).
