### ISSUE TITLE
bug: hardhat is not recognised for wagmi-cli

### ISSUE THREAD

**Issue by technophile-04** [wagmi-dev/wagmi#1877]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.1.6

### Current Behavior

We are trying to use `@wagmi/cli` in our project which is a monorepo, when you run `yarn wagmi generate` it gives your the following error : 
```js
⠹ Validating plugins
hardhat must be installed to use Hardhat plugin.
To install, run: npm install --save hardhat
``` 

### Expected Behavior

Since `hardhat` is a present dependency it should work. 

Currently, we have `hardhat` as our `devDependency` but even if you move to `dependencies` it doesn't work. Tried adding `hardhat` as different dependencies but it dosen't work. 

check this discussion for more info -> https://github.com/scaffold-eth/se-2/issues/116#issuecomment-1426819707

### Steps To Reproduce

clone the repo -> https://github.com/scaffold-eth/se-2 and switch to `feat/wagmi-cli` branch. 

1. clone the repo and move into se-2 directory 
```sh
git clone https://github.com/scaffold-eth/se-2
cd se-2
```

2. Switch to [`feat/wagmi-cli`](https://github.com/scaffold-eth/se-2/tree/feat/wagmi-cli) branch 
```sh
git switch feat/wagmi-cli
```
3. `yarn install`
4.  `yarn chain`
5. `yarn deploy` (in new terminal)
6. `yarn wagmi generate` (will error out)

check this discussion for more info -> https://github.com/scaffold-eth/se-2/issues/116#issuecomment-1426819707

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://github.com/scaffold-eth/se-2

### Anything else?

![Screenshot 2023-02-19 at 9 22 11 AM](https://user-images.githubusercontent.com/80153681/219917894-713378c4-974f-4def-bb54-afafab574053.jpg)

PS : If you do `npm install --save hardhat` in `packages/hardhat` and run `yarn install` after it works nicely but don't want to do it 🙌 

Thanks 🙏

**Comment by roninjin10** [comment]
@tmm @technophile-04 I looked at this and I think I got a quick fix

**Comment by roninjin10** [comment]
https://github.com/wagmi-dev/wagmi/pull/1884

**Comment by jxom** [comment]
Fixed via #1884 thanks to @roninjin10! Let us know if there are any further issues.

**Comment by technophile-04** [comment]
Thanks @roninjin10  and @jxom , but still getting same error :( ....This time it says to do `yarn add hardhat` though 

![Screenshot 2023-02-20 at 7 23 16 AM](https://user-images.githubusercontent.com/80153681/219991553-bd5b986f-37bc-4154-a3ad-d83933afa400.jpg)

Steps to reproduce are same as mentioned in this comment -> https://github.com/wagmi-dev/wagmi/issues/1877#issue-1590550293

PS : I have updated the [`feat/wagmi-cli`](https://github.com/scaffold-eth/se-2/tree/feat/wagmi-cli) with new version of @wagmi/cli -> 0.1.8

**Comment by roninjin10** [comment]
Hm let me look really quick

**Comment by roninjin10** [comment]
The bug now is `yarn list` exists in yarn1.0 but doesn't exist in yarn berry 
<img width="578" alt="image" src="https://user-images.githubusercontent.com/35039927/219993516-c594df91-94b6-4a20-9e45-c6f69cb1f92e.png">

**Comment by roninjin10** [comment]
[Another fix here](https://github.com/wagmi-dev/wagmi/pull/1886).  I verified your build should build after this gets in @technophile-04 
<img width="606" alt="image" src="https://user-images.githubusercontent.com/35039927/219996763-fbf1b902-3a40-4e8e-b871-24b15f7638ae.png">

**Comment by zkSoju** [comment]
Hey 

> [Another fix here](https://github.com/wagmi-dev/wagmi/pull/1886). I verified your build should build after this gets in @technophile-04 <img alt="image" width="606" src="https://user-images.githubusercontent.com/35039927/219996763-fbf1b902-3a40-4e8e-b871-24b15f7638ae.png">

It seems I'm still running into the `yarn install hardhat` error on the `0.1.10` cli.

**Comment by tmm** [comment]
@zkSoju what's the issue? Looks like it's generating an output in your screenshot.

**Comment by zkSoju** [comment]
> @zkSoju what's the issue? Looks like it's generating an output in your screenshot.
ah that wasn't my screenshot, I was just replying

![image](https://user-images.githubusercontent.com/28630104/221681428-807f33bb-bee6-4bdc-9691-3fcc3a03e42d.png)

**Comment by tmm** [comment]
What version of Yarn are you using? Can you add a minimal reproducible example?

**Comment by technophile-04** [comment]
> It seems I'm still running into the yarn install hardhat error on the 0.1.10 cli.

I think it solved for us checkout -> https://github.com/scaffold-eth/se-2/tree/feat/wagmi-cli#quickstart we are using `0.1.11` which is latest and it works for latest version too.... `0.1.9` was the version which resolved it. 

As Tmm suggested, it would be great if you share url of your repo.

**Comment by LilaRest** [comment]
Hi there! I'm experiencing the exact same bug during the Vercel deployment of [this project](https://github.com/ledgity-labs/Ledgity-DeFi). Hardhat seems properly installed by the `pnpm install` command.

Here are related logs:
```
(HIDDEN PART)
[11:15:24.517] dependencies:
(HIDDEN PART)
[11:15:24.518] - @wagmi/core 1.3.7
[11:15:24.518] + @wagmi/core 1.3.8
[11:15:24.518] - viem 1.2.14
[11:15:24.518] + viem 1.4.2
[11:15:24.518] - wagmi 1.3.8
[11:15:24.518] + wagmi 1.3.9
(HIDDEN PART)
[11:15:24.518] 
[11:15:24.518] devDependencies:
(HIDDEN PART)
[11:15:24.519] - hardhat 2.16.1
[11:15:24.519] + hardhat 2.17.0
[11:15:24.519] + hardhat-contract-sizer 2.10.0
(HIDDEN PART)
[11:15:24.520] 
[11:15:24.542] Done in 21.6s
[11:15:24.569] Detected Next.js version: 13.4.9
[11:15:24.655] Running "pnpm run build"
[11:15:25.171] 
[11:15:25.171] > ledgity-defi@1.124.2 build /vercel/path0
[11:15:25.171] > pnpm cc:compile && next build
[11:15:25.171] 
[11:15:25.674] 
[11:15:25.674] > ledgity-defi@1.124.2 cc:compile /vercel/path0
[11:15:25.674] > hardhat compile && wagmi generate && ts-node ./contracts/extract-abis.ts
[11:15:25.674] 
[11:15:26.710] Downloading compiler 0.8.18
[11:15:31.104] Generating typings for: 42 artifacts in dir: typechain-types for target: ethers-v6
[11:15:33.455] Successfully generated 126 typings!
[11:15:33.462] Compiled 42 Solidity files successfully
[11:15:34.118] - Validating plugins
[11:15:34.929] [31m
[11:15:34.929] hardhat must be installed to use Hardhat plugin.
[11:15:34.929] To install, run: pnpm add hardhat[39m
```

**Comment by LilaRest** [comment]
> @LilaRest please create a new issue with a minimal reproduction instead of commenting on older issues.

Sure I will!

**Comment by RasenGUY** [comment]
im having the same issuue but with npm:
node: v18.17.1
npm:  v9.6.7

when running hardhat npx wagmi generate im getting the same error as @technophile-04.

**Comment by mpaler** [comment]
see https://github.com/egoist/detect-package-manager/issues/13
