### ISSUE TITLE
bug: pnpm wagmi init `Cannot find module` issue

### ISSUE THREAD

**Issue by didostap** [wagmi-dev/wagmi#2288]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.0.0

### Current Behavior

Hey guys. I'm excited about the `v1.0.0` with `viem`, but looks like it doesn't work properly yet.
I'm trying to init with `@wagmi/cli` but receive cannot find module error

### Expected Behavior

init without error

### Steps To Reproduce

1. run `pnpm i -D @wagmi/cli` (`v1.0.0`)
2. run `pnpm wagmi init`
3. receive an error
<img width="1194" alt="Screenshot 2023-05-09 at 13 58 02" src="https://user-images.githubusercontent.com/49234191/237013353-bec1df3e-0e65-49e4-bdb5-8362dfb992fe.png">

**Comment by jxom** [comment]
Fixed in 1.0.1!

**Comment by MrKampla** [comment]
I'm still getting this error in 1.0.3, `exports` section in package.json still points to index.mts

**Comment by tmm** [comment]
New issue tracking this: https://github.com/wagmi-dev/wagmi/issues/2450#issuecomment-1567323117
