### ISSUE TITLE
bug: useWaitForTransactionReceipt() hook seems to not refresh data and ignore poolingInterval

### ISSUE THREAD

**Issue by clumsier** [wagmi-dev/wagmi#3219]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

2.0.0-beta.1 

### Current Behavior

As in title seems useWaitForTransactionReceipt() hook state is stuck on "pending" it also seems to ignore `poolingInterval` param so query is not refetched. I've tried to use `refetch` but I get inconsistent results where newer txes seems to still not have any data returned, old ones sometimes have it, sometimes don't.

### Expected Behavior

useWaitForTransactionReceipt() should refresh it's data automatically.

### Steps To Reproduce

I'm using such custom hooks to combine write with simulate/unprepared data to indicate txes with spinner + confirm alerts to user so you could just copy paste that and perform some writeTx.

I've tested it on Goerli, Polygon Mainnet, Polygon Mumbai and Ronin network.

```
import { useEffect } from 'react';
import { TransactionReceipt, WriteContractReturnType } from 'viem';
import { useWaitForTransactionReceipt, useWriteContract } from 'wagmi';

export type ContractWriteWithTracking = {
  onInProgress: (data: WriteContractReturnType) => void;
  onCompleted: (data: TransactionReceipt | undefined) => void;
};

export function useWriteContractWithTracking({
  dataSimulate,
  onInProgress,
  onCompleted,
}: {
  // TO DO, some way to have it non any, any?
  // dataSimulate: UseSimulateContractReturnType<Abi>['data'];
  dataSimulate: any;
} & ContractWriteWithTracking) {
  const { data: hash, writeContract } = useWriteContract({
    mutation: {
      onSuccess: onInProgress,
    },
  });

  const { data: dataConfirmed } = useWaitForTransactionReceipt({
    hash,
  });

  useEffect(() => {
    if (dataConfirmed) {
      onCompleted(dataConfirmed);
    }
  }, [dataConfirmed]);

  return {
    writeContract: dataSimulate?.request ? () => writeContract(dataSimulate.request) : undefined,
    txHash: hash,
  };
}

export function useWriteContractUnpreparedWithTracking({
  onInProgress,
  onCompleted,
}: ContractWriteWithTracking) {
  const { data: hash, writeContract } = useWriteContract({
    mutation: {
      onSuccess: onInProgress,
    },
  });

  const { data: dataConfirmed } = useWaitForTransactionReceipt({
    hash,
  });

  useEffect(() => {
    if (dataConfirmed) {
      onCompleted(dataConfirmed);
    }
  }, [dataConfirmed]);

  return {
    writeContract,
    txHash: hash,
  };
}
```

**Comment by tmm** [comment]
Appreciate you trying out the beta! Can you try out the latest beta - `npm i wagmi@beta viem@beta`?

If this still doesn't work, please comment with a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and I'm happy to re-open.

It will save us a lot of time reproducing your config & environment, and trying to reproduce your issue. See [Why reproductions are required](https://antfu.me/posts/why-reproductions-are-required).

**Comment by tmm** [comment]
You need to either pass [`transports`](https://beta.wagmi.sh/react/api/createConfig#transports) or [`client`](https://beta.wagmi.sh/react/api/createConfig#client) to `createConfig`. Also, make sure you pass a non-public RPC service (e.g. Alchemy, QuickNode, et al) since public RPCs tend to have aggressive caching and not resolve new data immediately (what is happening here).

**Comment by clumsier** [comment]
@tmm yeah, I forgot to add it. However it doesn't make any difference, eg. I just tested it with custom Alchemy Key:

```
transports: {
    [goerli.id]: http('https://eth-goerli.g.alchemy.com/v2/myApiKey'),
  },
```

I can see proper requests in network tab with this key being made eg. for ens avatar
![image](https://github.com/wagmi-dev/wagmi/assets/106453298/8f59f339-ac4d-41ca-81ca-ebdde96aad44)

but I'm still encounterhing an issue where there is no data from `useWait...`

**Comment by tmm** [comment]
Will take another look!

**Comment by tmm** [comment]
This looks like it will fix it https://github.com/wagmi-dev/wagmi/pull/3188

**Comment by tmm** [comment]
`[2.0.0-beta.5](https://www.npmjs.com/package/wagmi/v/2.0.0-beta.5)` should fix this. Let me know if it doesn't!

**Comment by clumsier** [comment]
@tmm just updated repo and issue still persists.

Added `NEXT_PUBLIC_GOERLI_RPC` env variable so you could test with your key inside `.env.local` file.

I had to also add `mounted` logic for whole page which is utilizing wagmi hooks as I was getting:
```
Error: Missing getServerSnapshot, which is required for server-rendered content. Will revert to client rendering.
``` even tho `ssr: true` is set on config

You can see error when you set `true` as default value instead of `false`:
`const [mounted, setMounted] = useState(false);`

**Comment by tmm** [comment]
You `yarn.lock` has Wagmi set to an earlier version.

```
$ yarn
$ yarn why wagmi
=> Found "wagmi@2.0.0"
```

If you install the correct version, you can remove `mounted` and I'm guessing `useWaitForTransactionReceipt` will work as well.

```
$ yarn add wagmi@beta
$ yarn why wagmi
=> Found "wagmi@2.0.0-beta.5"
```

**Comment by clumsier** [comment]
@tmm thanks for this catch and help, idk how I missed it - can confirm that now it works!

Btw. awesome work on beta for both wagmi and viem, it makes working with web3 to feel like a breeze! :)
