### ISSUE TITLE
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

### ISSUE THREAD

**Issue by victorvu18** [wagmi-dev/wagmi#3232]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

^1.4.7

### Current Behavior

`./node_modules/node-gyp-build/index.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

Import trace for requested module:
./node_modules/node-gyp-build/index.js
./node_modules/bufferutil/index.js
./node_modules/isows/node_modules/ws/lib/buffer-util.js
./node_modules/isows/node_modules/ws/lib/receiver.js
./node_modules/isows/node_modules/ws/wrapper.mjs
./node_modules/isows/_esm/index.js
./node_modules/viem/_esm/utils/rpc.js
./node_modules/viem/_esm/clients/transports/http.js
./node_modules/viem/_esm/index.js
./node_modules/viem/_esm/utils/encoding/toRlp.js
./node_modules/viem/_esm/chains/celo/serializers.js
./node_modules/viem/_esm/chains/definitions/celo.js
./node_modules/viem/_esm/chains/index.js
./node_modules/wagmi/dist/index.js
./src/context/web_3_modal.tsx`

### Steps To Reproduce

i use web3modal and nextjs 13 for my project. below is dependencies of my package.jon file:
`
"dependencies": {
    "@web3modal/ethereum": "^2.7.1",
    "@web3modal/react": "^2.7.1",
    "@web3modal/wagmi": "^3.3.2",
    "next": "13.5.6",
    "react": "^18",
    "react-dom": "^18",
    "viem": "^1.19.3",
    "wagmi": "^1.4.7"
  }`

How can i fix this bug???

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.

**Comment by victorvu18** [comment]
i fixed this. Add `unknownContextCritical = false` to webpack.

**Comment by MeanBoyCousin** [comment]
@tmm I've put together an MRE relating to OPs problem as I am having the same issue. Whilst the answer from @victorvu18 does work, seems like it's just suppressing the actual issue.

[Link to MRE.](https://github.com/MeanBoyCousin/wagmi-mre)

It's just a basic Next app with no customisation. Simply `yarn` install and then run `yarn dev`. Once you navigate to localhost and load the homepage, you should see the issue in the terminal. For additional reference, I am seeing the following.

```sh
 ⚠ ./node_modules/node-gyp-build/index.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

Import trace for requested module:
./node_modules/node-gyp-build/index.js
./node_modules/utf-8-validate/index.js
./node_modules/isows/node_modules/ws/lib/validation.js
./node_modules/isows/node_modules/ws/lib/receiver.js
./node_modules/isows/node_modules/ws/wrapper.mjs
./node_modules/isows/_esm/index.js
./node_modules/viem/_esm/utils/rpc.js
./node_modules/viem/_esm/clients/transports/http.js
./node_modules/viem/_esm/index.js
./node_modules/@wagmi/core/dist/chunk-TSH6VVF4.js
./node_modules/@wagmi/core/dist/internal/index.js
./node_modules/wagmi/dist/index.js
./src/Wagmi/index.tsx
 ⚠ ./node_modules/node-gyp-build/index.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

Import trace for requested module:
./node_modules/node-gyp-build/index.js
./node_modules/utf-8-validate/index.js
./node_modules/isows/node_modules/ws/lib/validation.js
./node_modules/isows/node_modules/ws/lib/receiver.js
./node_modules/isows/node_modules/ws/wrapper.mjs
./node_modules/isows/_esm/index.js
./node_modules/viem/_esm/utils/rpc.js
./node_modules/viem/_esm/clients/transports/http.js
./node_modules/viem/_esm/index.js
./node_modules/@wagmi/core/dist/chunk-TSH6VVF4.js
./node_modules/@wagmi/core/dist/internal/index.js
./node_modules/wagmi/dist/index.js
./src/Wagmi/index.tsx
 ⚠ ./node_modules/node-gyp-build/index.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

Import trace for requested module:
./node_modules/node-gyp-build/index.js
./node_modules/utf-8-validate/index.js
./node_modules/isows/node_modules/ws/lib/validation.js
./node_modules/isows/node_modules/ws/lib/receiver.js
./node_modules/isows/node_modules/ws/wrapper.mjs
./node_modules/isows/_esm/index.js
./node_modules/viem/_esm/utils/rpc.js
./node_modules/viem/_esm/clients/transports/http.js
./node_modules/viem/_esm/index.js
./node_modules/@wagmi/core/dist/chunk-TSH6VVF4.js
./node_modules/@wagmi/core/dist/index.js
./node_modules/wagmi/dist/index.js
./src/Wagmi/index.tsx
```

**Comment by glitch-txs** [comment]
@MeanBoyCousin I'm not seeing wagmi in your MRE, maybe you forgot to push changes?

**Comment by glitch-txs** [comment]
I created an MRE here as well, the errors are shown on the server console
https://github.com/glitch-txs/wagminext-mre

**Comment by nekotoriy** [comment]
Hello!

Added repro links

Also adding one more repro link

https://stackblitz.com/edit/stackblitz-starters-xn5ytm?description=The%20React%20framework%20for%20production&file=package.json&title=Next.js%20Starter

**Comment by nekotoriy** [comment]
Hello, @tmm !

Added repro links

Also adding one more repro link

https://stackblitz.com/edit/stackblitz-starters-xn5ytm?description=The%20React%20framework%20for%20production&file=package.json&title=Next.js%20Starter

**Comment by gonghaibo** [comment]
`/** @type {import('next').NextConfig} */
const nextConfig = {
    webpack: config => {
        config.resolve.fallback = { fs: false, net: false, tls: false };
        config.externals.push('pino-pretty', 'lokijs', 'encoding');
        config.module.unknownContextCritical = false;
        return config;
    },
};

module.exports = nextConfig;`

Complete solution.

**Comment by nekotoriy** [comment]
Hello @gonghaibo!

Thanks, but it's not a solution, seems like workaround.

I think it should be fixed.
